use northwindmysql;

--32
SELECT DISTINCT C.CUSTOMERID, C.COMPANYNAME, O.ORDERID, SUM(OD.UNITPRICE * OD.QUANTITY) AS TOTALORDERAMOUNT
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS AS OD ON O.ORDERID = OD.ORDERID
WHERE YEAR(O.ORDERDATE) = 2016
GROUP BY 
O.ORDERID,
C.CUSTOMERID,
C.COMPANYNAME
HAVING TOTALORDERAMOUNT >= 10000;

--33 AND 34 MIX - JUST SPLIT AS PER REQUIREMENTS
SELECT DISTINCT C.CUSTOMERID, C.COMPANYNAME, SUM(OD.UNITPRICE * OD.QUANTITY) AS TOTALORDERAMOUNT, 
SUM((OD.UNITPRICE * OD.QUANTITY) - (OD.DISCOUNT * (OD.UNITPRICE * OD.QUANTITY))) AS TOTALORDERAMOUNTWITHDISCOUNT
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS AS OD ON O.ORDERID = OD.ORDERID
WHERE YEAR(O.ORDERDATE) = 2016
GROUP BY
C.CUSTOMERID,
C.COMPANYNAME
HAVING TOTALORDERAMOUNT >= 15000
ORDER BY TOTALORDERAMOUNTWITHDISCOUNT DESC;

--35
SELECT
    EmployeeID,
    OrderID,
    OrderDate
FROM
    Orders
WHERE
    -- Compare the date part of OrderDate with the last day of its month
    DATE(OrderDate) = LAST_DAY(OrderDate)
ORDER BY
    EmployeeID,
    OrderID;


--36
SELECT O.ORDERID, COUNT(OD.ORDERID) AS NUMBEROFITEMS
FROM ORDERS AS O
JOIN ORDERDETAILS AS OD ON O.ORDERID = OD.ORDERID
GROUP BY O.ORDERID
ORDER BY NUMBEROFITEMS
LIMIT 10;

--37
