use northwindmysql;

-- 20
select categoryname, count(p.productname) as numberofproducts from categories as c 
join products as p on c.categoryid = p.categoryid
group by c.categoryid;

--21
select country, city, count(customerid) totalcustomer from customers 
group by country, city;


--22
select productid, productname, unitsinstock, reorderlevel from products WHERE
unitsinstock < reorderlevel 
order by productid;

--23
SELECT PRODUCTID, PRODUCTNAME, UNITSINSTOCK, UNITSONORDER, REORDERLEVEL, DISCONTINUED
FROM PRODUCTS
WHERE (UNITSINSTOCK + UNITSONORDER) <= REORDERLEVEL
AND 
DISCONTINUED = 0;


--24
-- SELECT CUSTOMERID, COMPANYNAME, REGION FROM CUSTOMERS
-- ORDER BY REGION , COMPANYNAME;

SELECT CUSTOMERID, COMPANYNAME, REGION FROM CUSTOMERS 
ORDER BY
CASE WHEN REGION IS NULL THEN 1 ELSE 0 END ASC,
REGION ASC,
COMPANYNAME ASC;


--25
SELECT SHIPCOUNTRY, AVG(FREIGHT) AS AVERAGEFREIGHT 
FROM ORDERS
GROUP BY SHIPCOUNTRY
ORDER BY AVERAGEFREIGHT DESC
LIMIT 3;

--26
SELECT SHIPCOUNTRY, AVG(FREIGHT) AS AVERAGEFREIGHT 
FROM ORDERS
WHERE YEAR(ORDERDATE) = 2015
GROUP BY SHIPCOUNTRY
ORDER BY AVERAGEFREIGHT DESC
LIMIT 3;

--27
-- TEACHES HOW WE CANNOT USE BETWEEN 

--28
SELECT SHIPCOUNTRY, AVG(FREIGHT) AS AVERAGEFREIGHT 
FROM ORDERS
WHERE ORDERDATE > DATE_SUB((SELECT MAX(ORDERDATE) FROM ORDERS), INTERVAL 12 MONTH)
GROUP BY SHIPCOUNTRY
ORDER BY AVERAGEFREIGHT DESC
LIMIT 3;


--29
SELECT E.EMPLOYEEID, E.LASTNAME, O.ORDERID, P.PRODUCTNAME, OD.QUANTITY
FROM EMPLOYEES AS E
JOIN ORDERS AS O ON E.EMPLOYEEID = O.EMPLOYEEID
JOIN ORDERDETAILS AS OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS AS P ON OD.PRODUCTID = P.PRODUCTID;

--30
SELECT C.CUSTOMERID AS CUSTOMERS_CUSTOMERID, O.CUSTOMERID AS ORDERS_CUSTOMERID
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O ON 
C.CUSTOMERID = O.CUSTOMERID
WHERE O.CUSTOMERID IS NULL;

--31

SELECT C.CUSTOMERID, O.CUSTOMERID
FROM CUSTOMERS AS C 
LEFT JOIN ORDERS AS O ON C.CUSTOMERID = O.CUSTOMERID AND O.EMPLOYEEID = 4
WHERE O.CUSTOMERID IS NULL;

-- (SELECT EMPLOYEEID FROM EMPLOYEES WHERE ) 